name: Continuous Integration

on:
  # if any push on main branch
  push:
    branches:
  # if any pull request on main branch
  pull_request:


jobs:
# Job for Backend
  backend-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # see what node versions are supported by our application
        node-version: []   # node version we are testing ( must be >20 )

    defaults:
      run:
        # asking to check the code in the backend folder
        working-directory: ./backend

    steps:
      # get the code from the repo
      - name : Checkout Code
        uses :              # github action to get in the repos root folder

      # install nodejs
      - name : Setup Node.js
        uses :              # github action to install nodejs
        with:
          node-version : {{matrix.node-version}} # refernce the node-version set above
          cache :           # command to install the node packages
          cache-dependency-path :           # path to the package file


      # install dependencies
      - name : Install dependencies
        run :

      # generate prisma client
      - name : Prisma Client
        run :

      #  check the build
      - name : Build Check
        run :

# Job for Frontend
  frontend-ci :
    runs-on : ubuntu-latest
    strategy :
      matrix :
        # see what node versions are supported by our application
        node-version : [20.x,22.x,24.x]

    defaults :
      run:
        # asking to check the code in the frontend folder
        working-directory: ./frontend

    steps :
      - name : Check Code
        uses : actions/checkout@v4

      - name : Setup Node.js ${{ matrix.node-version }}
        uses : actions/setup-node@v4
        with:
          node-version : {{matrix.node-version}}
          cache :           # command to install the node packages
          cache-dependency-path :           # path to the package file

      - name : Install Dependencies
        run : npm install

      - name : Run Lint
        run :             # command to run lint

      - name : Build Check
        run :             # command to build the application 

